/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package loiseau.ihm;

import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Cell;
import jxl.Sheet;
import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.read.biff.BiffException;

/**
 *
 * @author Collette
 */
public class importPriseDeMesure extends javax.swing.JFrame {

    /**
     * Creates new form importPriseDeMesure
     */
    public importPriseDeMesure() {
        initComponents();
    }
    DefaultTableModel dtm;
    JFileChooser fc = new JFileChooser();
    WorkbookSettings ws = new WorkbookSettings();
    Workbook fichierCharge;
    Sheet sheet;
    static Vector<Vector> lesArticle = new Vector();
    Vector vArticle=new Vector();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticle = new javax.swing.JTable();
        txtDate = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        txtTel = new javax.swing.JTextField();
        cmdParcourir = new javax.swing.JButton();
        txtURL = new javax.swing.JTextField();
        jLabelDate = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelAdresse = new javax.swing.JLabel();
        jLabelTelephone = new javax.swing.JLabel();
        btnAjout = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblArticle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Type", "Largeur", "Hauteur"
            }
        ));
        jScrollPane1.setViewportView(tblArticle);

        cmdParcourir.setText("Parcourir...");
        cmdParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdParcourirActionPerformed(evt);
            }
        });

        txtURL.setForeground(new java.awt.Color(255, 255, 255));
        txtURL.setEnabled(false);

        jLabelDate.setText("Date");

        jLabelNom.setText("Nom");

        jLabelAdresse.setText("Adresse");

        jLabelTelephone.setText("Téléphone");

        btnAjout.setText("Ajouter");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDate)
                            .addComponent(jLabelNom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDate)
                            .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelAdresse)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTelephone)
                                .addGap(7, 7, 7)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtTel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .addComponent(txtAdresse))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtURL)
                        .addGap(18, 18, 18)
                        .addComponent(cmdParcourir)
                        .addGap(12, 12, 12)))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAjout))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdParcourir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDate)
                    .addComponent(jLabelAdresse))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNom)
                    .addComponent(jLabelTelephone))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAjout))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        // Instancie le dtm avec le jTable tblArticle
        dtm = (DefaultTableModel) tblArticle.getModel();
     
        // Encode le fichier excel
        ws.setEncoding("windows-1252");
    }//GEN-LAST:event_formWindowOpened

    private void cmdParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdParcourirActionPerformed
        // TODO add your handling code here:
        
        // Ouverture de la boite de dialogue "Parcourir..."
        int returnVal = fc.showOpenDialog(this);
        
           // Evenement de la boite de dialogue "Parcourir..."
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                
                //Chargement du fichier Excel
                String url = fc.getSelectedFile().getAbsolutePath();
                txtURL.setText(url);
                fichierCharge = Workbook.getWorkbook(new File(url), ws);
                sheet = fichierCharge.getSheet(0);
                
                // Appelle de la fontion qui récupere l'entête du fichier Exel
                recupInfosPriseDeMesure();
                
                  // Appelle de la fontion qui récupere les articles
                recupArticle();

            } catch (IOException ex) {
                Logger.getLogger(importPriseDeMesure.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BiffException ex) {
                Logger.getLogger(importPriseDeMesure.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdParcourirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(importPriseDeMesure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(importPriseDeMesure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(importPriseDeMesure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(importPriseDeMesure.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new importPriseDeMesure().setVisible(true);
            }
        });
    }

    public void recupInfosPriseDeMesure() {
        // Récupere et ajoute dans les textfiels la date, le nom, l'adresse, le téléphone
        txtDate.setText(sheet.getCell(2, 2).getContents());
        txtNom.setText(sheet.getCell(2, 3).getContents());
        txtAdresse.setText(sheet.getCell(2, 4).getContents());
        txtTel.setText(sheet.getCell(2, 5).getContents());
    }

    public void recupArticle() {
         // Parcourt tous les articles
        for (int i = 24; i < sheet.getRows(); i++) {
            Cell cell = sheet.getCell(0, i);
            if (cell.getContents() == "") {
                break;
            } else {
                // Créer un vecteur en y ajoutant le type, la largeur et la hauteur des articles
                vArticle = new Vector();
                vArticle.addElement(sheet.getCell(0, i).getContents());
                vArticle.addElement(sheet.getCell(1, i).getContents());
                vArticle.addElement(sheet.getCell(2, i).getContents());
                lesArticle.add(vArticle);
                // ajoute le vetceur vArticle au dtm
                dtm.addRow(vArticle);
                
            }
        }
    }
    public static Vector<Vector> openForm(Component cpt){
        lesArticle=null;
        importPriseDeMesure impor=new importPriseDeMesure();
        impor.setLocationRelativeTo(cpt);
        impor.setVisible(true);
        return lesArticle;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjout;
    private javax.swing.JButton cmdParcourir;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabelAdresse;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelTelephone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArticle;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtTel;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
