/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package loiseau.ihm;

import java.awt.Component;
import java.util.Vector;
import loiseau.stockage.Article_fabrication;
import loiseau.stockage.Option;

/**
 *
 * @author guillaume
 */
public class JDialogOptions extends javax.swing.JDialog {

    /**
     * Creates new form JDialogOptions
     */
    public JDialogOptions(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDialogOptions(java.awt.Frame parent, boolean modal, String unNom, String uneHauteur, String uneLargeur, Vector<Option> Option) {
        super(parent, modal);
        initComponents();
        nom = unNom;
        hauteur = uneHauteur;
        largeur = uneLargeur;
        lesOption = Option;
    }
    static Article_fabrication art;
    String nom;
    String hauteur;
    String largeur;
    Vector<Option> lesOption;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbbOption = new javax.swing.JComboBox();
        txtNom = new javax.swing.JTextField();
        txtLargeur = new javax.swing.JTextField();
        txtHauteur = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAjout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtHauteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHauteurActionPerformed(evt);
            }
        });

        jLabel1.setText("Nom de L'article");

        jLabel2.setText("Largeur de l'article");

        jLabel3.setText("Hauteur de l'article");

        btnAjout.setText("Ajouter");
        btnAjout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbbOption, 0, 227, Short.MAX_VALUE)
                        .addComponent(txtNom)
                        .addComponent(txtLargeur)
                        .addComponent(txtHauteur)))
                .addContainerGap(124, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAjout))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(cbbOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLargeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtHauteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnAjout))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHauteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHauteurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHauteurActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for (Option o : lesOption) {
            cbbOption.addItem(o.getNom_option());
        }
        txtNom.setText(nom);
        txtLargeur.setText(largeur);
        txtHauteur.setText(hauteur);
    }//GEN-LAST:event_formWindowOpened

    private void btnAjoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjoutMouseClicked
        // TODO add your handling code here:
        art = new Article_fabrication();
        art.setHauteur(Double.valueOf(txtHauteur.getText()));
        art.setLargeur(Double.valueOf(txtLargeur.getText()));
        nom = cbbOption.getSelectedItem().toString().concat(" pour " + nom);
        art.setNom(nom);
        art.setQuantite(1);
        art.setRef_article("option");
        art.setPrix(lesOption.get(cbbOption.getSelectedIndex()).getPrix_option());
        art.setType_article(5);
        art.setPuissance_moteur(0);
        art.setCouleur_coffre(0);
        art.setCouleur_coulisse(0);
        art.setCote_manoeuvre("0");
        art.setType_coulisse(0);
        art.setType_manoeuvre(0);
        art.setCouleur_tablier(0);
        art.setType_lame(0);
        art.setTelecommande(0);
        art.setHors_cote(0);
        art.setType_pose(0);
        art.setType_moteur("0");
        dispose();
    }//GEN-LAST:event_btnAjoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static Article_fabrication openForm(Component cpt, String unNom, String uneHauteur, String uneLargeur, Vector<Option> Option) {
        art = null;
        JDialogOptions dialOption = new JDialogOptions(null, true, unNom, uneHauteur, uneLargeur, Option);
        dialOption.setLocationRelativeTo(cpt);
        dialOption.setVisible(true);
        return art;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogOptions dialog = new JDialogOptions(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjout;
    private javax.swing.JComboBox cbbOption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtHauteur;
    private javax.swing.JTextField txtLargeur;
    private javax.swing.JTextField txtNom;
    // End of variables declaration//GEN-END:variables
}
